.changeset/twelve-garlics-clap.md, packages/next-admin/src/components/DataTable.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/index.tsx, packages/next-admin/src/router.tsx, packages/next-admin/src/utils/jsonSchema.ts, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/server.ts
=> refactor: ressource -> resource

.changeset/hide-models.md, apps/docs/pages/docs/api-docs.mdx, packages/next-admin/src/router.tsx, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/server.ts
Fix https://github.com/premieroctet/next-admin/issues/15
=> feat: hide models that are not defined in admin options

.changeset/itchy-laws-refuse.md, packages/next-admin/package.json, packages/next-admin/src/components/NextAdmin.tsx, yarn.lock
See https://github.com/premieroctet/next-admin/issues/27
https://github.com/premieroctet/next-admin/assets/686101/03ef6118-d0b3-4fe1-8a80-198c5f847ce0
=> feat: loading indicator on client side navigation

.changeset/wet-masks-kick.md, apps/docs/pages/docs/api-docs.mdx, apps/example/pages/admindemo/[[...nextadmin]].tsx, packages/next-admin/src/components/Cell.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/exceptions/ValidationError.ts, packages/next-admin/src/router.tsx, packages/next-admin/src/tests/serverUtils.test.ts, packages/next-admin/src/types.ts, packages/next-admin/src/utils/server.ts, packages/next-admin/src/utils/validator.test.ts, packages/next-admin/src/utils/validator.ts
See https://github.com/premieroctet/next-admin/issues/26
=> feat: data server validation

.env, .prettierrc, apps/docs/pages/index.mdx, apps/example/e2e/crud.spec.ts, apps/example/e2e/utils.ts, apps/example/pages/admin/[[...nextadmin]].tsx, apps/example/pages/index.tsx, apps/example/prisma/json-schema/json-schema.json, apps/example/prisma/migrations/20230907085437_rename_user_model/migration.sql, apps/example/prisma/schema.prisma, package.json, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/TableHead.tsx, packages/next-admin/src/components/radix/Table.tsx, packages/next-admin/src/utils/validator.test.ts
- Capitalize label / add max-width for table cell
- Change the url from `/admindemo` to `/admin`
- Add prettier config
- Rename demo model from `user` to `User` for consistency
=> Improve ui and demo

.env, .env.example, apps/example/prisma/schema.prisma
Switch to vercel postgres for demo
=> feat: use vercel pg for demo

.changeset/young-chicken-beam.md, apps/example/pages/admin/[[...nextadmin]].tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/router.tsx, packages/next-admin/src/tests/serverUtils.test.ts, packages/next-admin/src/tests/singleton.ts, packages/next-admin/src/types.ts, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/server.ts
**Issue**
#58 
**Changes**
- Add ability to choose format type for `Date` property between `date-time` and `date`
- Open options to extension based on property type
- Introduce handler object to handle custom logic for a property in edit mode
=> Add Date format for 'date-time' and 'date'

.changeset/witty-penguins-camp.md, .github/workflows/e2e.yml, apps/example/e2e/utils.ts, packages/next-admin/src/components/DataTable.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/router.tsx, packages/next-admin/src/tests/prismaUtils.test.ts, packages/next-admin/src/utils/server.test.ts, packages/next-admin/src/utils/server.ts
=> feat: allow slug version of model in url

.changeset/nine-panthers-bow.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
=> feat: override model name in UI

.changeset/tame-wasps-sparkle.md, packages/next-admin/src/types.ts, packages/next-admin/src/utils/prisma.ts
=> feat: allow sort by relationship count

.changeset/tall-guests-jam.md, apps/example/components/JsonEditor.tsx, apps/example/options.tsx, apps/example/package.json, apps/example/prisma/json-schema/json-schema.json, apps/example/prisma/migrations/20231208102028_user_metadata/migration.sql, apps/example/prisma/schema.prisma, packages/next-admin/src/tests/serverUtils.test.ts, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts, yarn.lock
=> feat: add support for json fields

.changeset/nasty-toys-learn.md, .changeset/shiny-phones-attend.md, .changeset/twenty-years-kneel.md, apps/example/components/DatePicker.tsx, apps/example/components/JsonEditor.tsx, apps/example/e2e/utils.ts, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, apps/example/prisma/schema.prisma, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/inputs/MultiSelectWidget.tsx, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/components/inputs/Selector.tsx, packages/next-admin/src/context/FormContext.tsx, packages/next-admin/src/router.tsx, packages/next-admin/src/tests/prismaUtils.test.ts, packages/next-admin/src/tests/serverUtils.test.ts, packages/next-admin/src/tests/singleton.tsx, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts
To allow server side search in select
=> Store formData in context

.changeset/pretty-melons-develop.md, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts
Issue:
#105 
Changes:
- Order fields in form based on order in `display` options
=> Order fields in form

.changeset/mighty-elephants-cheat.md, packages/next-admin/src/utils/server.ts
=> Fix parse error on relationship

.changeset/many-ladybugs-tickle.md, packages/next-admin/src/utils/server.ts
=> Fix optional relationship on form creation

.changeset/ninety-icons-appear.md, packages/next-admin/src/components/List.tsx
**Issue**
#118
**Change**
- Similar to same way as PR #123, possibility to hide all columns, even the id property column
=> Possibility hide even id column in form

.changeset/strange-games-march.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
**Issue**
#106 
**Change**
- Add aliases options to rename columns name and form label
=> Add aliases options to rename columns name and form label

.changeset/cuddly-moons-allow.md, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/server.ts
**Issue**
#125 
**Change**
- Add redirection on relationship fields
=> Add redirection on relationship fields

.changeset/gold-bees-search.md, apps/example/.env, docker-compose.yml, packages/next-admin/src/utils/server.ts
=> Support Decimal and Float Prisma

.changeset/long-pillows-confess.md, apps/example/options.tsx, apps/example/prisma/json-schema/json-schema.json, apps/example/prisma/migrations/20240129110259_add_rate/migration.sql, apps/example/prisma/schema.prisma, packages/next-admin/src/tests/prismaUtils.test.ts, packages/next-admin/src/utils/server.ts
**Comment**
https://github.com/premieroctet/next-admin/issues/128#issuecomment-1912160194
=> Fix table decimal, float and bigint

.changeset/new-nails-attack.md, packages/next-admin/src/tests/serverUtils.test.ts, packages/next-admin/src/types.ts, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts, packages/next-admin/src/utils/tools.ts
=> Add deep access for relationship formatter

.changeset/tidy-cameras-act.md, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/server.ts
=> Apply search on formatted field in form

.changeset/smart-monkeys-trade.md, packages/next-admin/src/components/List.tsx
=> Fix order alias

.changeset/plenty-knives-pull.md, packages/next-admin/src/components/inputs/FileWidget.tsx
=> fix: image display in file input field #154

.changeset/many-baboons-end.md, apps/docs/pages/docs/api-docs.mdx, packages/next-admin/src/actions/form.ts, packages/next-admin/src/router.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/server.ts
=> feat: add custom error message for upload handler #144

.changeset/lazy-olives-exercise.md, packages/next-admin/src/components/Cell.tsx, packages/next-admin/src/components/DataTable.tsx, packages/next-admin/src/components/common/Clipboard.tsx, packages/next-admin/src/hooks/useClipboard.ts
=> feat: add clipboard for table cells

.changeset/early-ligers-carry.md, apps/docs/pages/docs/_meta.json, apps/docs/pages/docs/i18n.mdx, apps/docs/pages/docs/theming.mdx, apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx, apps/example/options.tsx, apps/example/tailwind.config.js, packages/next-admin/src/components/ActionsDropdown.tsx, packages/next-admin/src/components/Cell.tsx, packages/next-admin/src/components/DataTable.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/Pagination.tsx, packages/next-admin/src/components/TableHead.tsx, packages/next-admin/src/components/common/Checkbox.tsx, packages/next-admin/src/components/common/Clipboard.tsx, packages/next-admin/src/components/inputs/CheckboxWidget.tsx, packages/next-admin/src/components/inputs/FileWidget.tsx, packages/next-admin/src/components/inputs/JsonField.tsx, packages/next-admin/src/components/inputs/MultiSelectWidget.tsx, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/components/inputs/Selector.tsx, packages/next-admin/src/components/inputs/SortButton.tsx, packages/next-admin/src/components/inputs/TextareaWidget.tsx, packages/next-admin/src/components/radix/Button.tsx, packages/next-admin/src/i18n.ts, packages/next-admin/tailwind.config.js
- update table ui
- update file input ui
- add animations to inputs
- add animations to dropdowns
- add the ability to set a custom primary color
=> feat: small ui revamp, add theming capability

apps/docs/components/Hero.tsx, apps/docs/pages/docs/getting-started.mdx
- Fix buttons layout on mobile (homepage) : 
- Move package installer commands in tabs
=> feat: improve doc and hp

.changeset/green-rats-sin.md, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
=> feat: configure global title

.changeset/tall-kangaroos-hammer.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
=> feat: add groups configuration in sidebar

.changeset/mean-books-punch.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/components/common/ResourceIcon.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
=> feat: add icons for resources in sidebar and titles

.changeset/friendly-fans-jog.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, packages/next-admin/package.json, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/inputs/NullField.tsx, packages/next-admin/src/components/radix/Tooltip.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/server.ts, yarn.lock
=> feat: add tooltip, helper text and notice

.changeset/sixty-dingos-fly.md, apps/docs/pages/docs/api-docs.mdx, apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx, apps/example/app/[locale]/admin/custom/page.tsx, apps/example/pages/pagerouter/admin/[[...nextadmin]].tsx, apps/example/pages/pagerouter/admin/custom/index.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/components/radix/Dropdown.tsx, packages/next-admin/src/types.ts
=> feat: add user informations & logout

.changeset/real-jokes-wash.md, apps/docs/pages/docs/api-docs.mdx, apps/example/options.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
=> feat: add option for external links in sidebar

.changeset/wicked-chicken-attack.md, packages/next-admin/src/components/Dashboard.tsx, packages/next-admin/src/components/NextAdmin.tsx
=> feat: redirect to first resource if dashboard doesnt exist

.changeset/shy-poets-remain.md, packages/next-admin/package.json, packages/next-admin/src/components/inputs/CheckboxWidget.tsx, packages/next-admin/src/components/inputs/RichText/RichTextField.tsx, packages/next-admin/src/components/inputs/RichText/utils.tsx, packages/next-admin/src/components/radix/Switch.tsx, yarn.lock
=> feat: update checkbox ui, fix rich text editor

.changeset/eighty-eggs-care.md, packages/next-admin/src/components/Menu.tsx
- add username ellipsis
- fix dividers
=> fix: ui fixes on Menu component

.changeset/witty-chefs-rhyme.md, packages/next-admin/src/components/Form.tsx
=> fix: label margin with input

.changeset/fresh-islands-hug.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/tests/tools.test.ts, packages/next-admin/src/utils/tools.ts
=> feat: add default label formatting

.changeset/cyan-boxes-smell.md, apps/example/pageRouterOptions.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/inputs/RichText/utils.tsx
=> fix: richtext html field render

.changeset/six-mice-bathe.md, apps/example/package.json, packages/next-admin/package.json, packages/next-admin/src/components/inputs/Selector.tsx, yarn.lock
=> chore: upgrade prisma-json-schema-generator dep

.changeset/warm-dryers-approve.md, .github/workflows/e2e.yml, apps/docs/pages/docs/api-docs.mdx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/prisma.ts
#223
Add a new `defaultSort` option for the list options
```typescript
{
User: {
list: {
defaultSort: {
field: "name",
direction: "desc"
}
}
}
}
```
=> feat: add default sort option

.changeset/hot-trains-dream.md, packages/next-admin/src/components/inputs/RichText/utils.tsx
#214 
Wraps plain strings in `p` tags for richtext-html format
=> fix: handle plain strings for rich text html

.changeset/small-rocks-drive.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Message.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts
Move alert message component
Fix some responsive style
No impact
=> Move alert message

.changeset/slimy-apples-grin.md, apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx, apps/example/app/[locale]/layout.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/components/inputs/RichText/RichTextField.tsx
Patch of some NextJS issue
- Remove dynamic metadata from appRouter
- `suppressHydrationWarning` on html tag in example
- Remove manual submission on form
- Add empty string as default value for RichTextEditor
=> Fix some next js issue

.changeset/grumpy-actors-push.md, packages/next-admin/src/hooks/useDataColumns.tsx, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts
Fix no fields options and resources error
#268 
No Impact
=> Fix no fields options error

.changeset/selfish-shoes-laugh.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts
Add slug inside breadcrumb
#263 
Add slug inside breadcrumb
Change breadcrumb if there is a `toString` function on model options
=> Add slug inside breadcrumb

.github/workflows/vercel-deploy.yml
[Linked issues]
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]
[Add screenshot of the changes you have made]
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
[Any additional information that reviewers should be aware of.]
=> Change workflow

.changeset/tough-balloons-teach.md, .changeset/unlucky-penguins-dress.md, packages/next-admin/package.json, packages/next-admin/src/components/Form.tsx
- Remove warning from HTML input
- Fill package information
#307 
No impact
=> Remove warning

CONTRIBUTING.md
=> Change CONTRIBUTING doc

.changeset/pretty-walls-lick.md, apps/example/app/[locale]/layout.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/preset.ts
Update preset to apply background on body, add button in form header to create new resource
- Add a new button in the form header page to create a new resource from the edit page
- Update the preset to that the background from the theme applies on the body by default
=> feat: improve preset and form

.changeset/great-zoos-count.md, .changeset/mean-clouds-study.md, apps/docs/pages/docs/_meta.json, apps/docs/pages/docs/api-docs.mdx, apps/docs/pages/docs/code-snippets.mdx, apps/example/actions/nextadmin.ts, apps/example/app/api/posts/export/route.ts, apps/example/app/api/users/export/route.ts, apps/example/components/DatePicker.tsx, apps/example/messages/fr.json, apps/example/options.tsx, packages/next-admin/src/components/ExportDropdown.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/i18n.ts, packages/next-admin/src/types.ts
- Add export button system
- Add code snippets in doc
#265 
Add API endpoint to export the data of a model, you can specify multiple format, in this case it will display as a dropdown in the UI.
No impact
=> Add export button system and code snippets

.changeset/eighty-dogs-fix.md, apps/example/e2e/002-table.spec.ts, apps/example/e2e/utils.ts, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, apps/example/prisma/seed.ts, packages/next-admin/src/utils/prisma.ts
Fix search when options search is not set 
More test end2end to that task
=> Fix search and add test to search

.changeset/polite-bulldogs-mate.md, apps/docs/pages/docs/i18n.mdx, apps/example/messages/fr.json, apps/example/options.tsx, packages/next-admin/src/components/EmptyState.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/inputs/Selector.tsx, packages/next-admin/src/context/I18nContext.tsx, packages/next-admin/src/hooks/useDataColumns.tsx, packages/next-admin/src/i18n.ts
Add possibility to translate model names and field names
- New translations keys 
- Handle all model and fields as a translations keys
No Impact
=> Add possibility to translate model names and field names

.changeset/slimy-pandas-do.md, apps/example/e2e/fields-form.spec.ts, apps/example/e2e/utils.ts, packages/next-admin/package.json, packages/next-admin/src/components/inputs/CheckboxWidget.tsx, packages/next-admin/src/components/radix/Switch.tsx, packages/next-admin/src/utils/server.ts
Fix boolean field
#329
No impact
- Add end2end test to check formData values after value of boolean changes
=> Fix boolean field

.changeset/four-ears-repeat.md, apps/example/e2e/utils.ts, packages/next-admin/src/components/inputs/MultiSelect/MultiSelectDisplayListItem.tsx, packages/next-admin/src/components/inputs/MultiSelect/MultiSelectItem.tsx, packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/components/inputs/Selector.tsx
Fix selector fields for enum and relationships. Click zone
Test e2e
No Impact
=> Fix selector fields for enum and relationships

.changeset/weak-planets-jam.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/utils/jsonSchema.ts
Fix disabled fields when default value
[Linked issues]
#340 
CRUD e2e tests
No impact
=> Fix disabled fields when default value

.changeset/beige-teachers-lay.md, packages/next-admin/src/components/inputs/RichText/RichTextField.tsx, packages/next-admin/src/components/inputs/TextareaWidget.tsx
Add resizable button and scroll Richtext and textarea fields 
#348 
No Impact
=> Add resizable button and scroll richtext

.changeset/silent-countries-behave.md, packages/next-admin/src/components/List.tsx
button visible depending on whether or not you have permission to delete
[Linked issues]
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]
[Add screenshot of the changes you have made]
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
[Any additional information that reviewers should be aware of.]
=> button visible depending on whether or not you have permission to delete

.changeset/strange-phones-beam.md, apps/example/options.tsx, packages/next-admin/package.json, packages/next-admin/src/components/Form.tsx, yarn.lock
Fix padding form
#356 
Remove padding around field, set default gap for form and use tw-merge to merge styles
No impact
=> Fix padding form

.changeset/soft-mugs-cover.md, apps/docs/pages/docs/api-docs.mdx, apps/example/actions/nextadmin.ts, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/server.ts, packages/next-admin/src/utils/tools.ts
=> Remove usage of `new File`

.changeset/strange-waves-rush.md, .github/workflows/reset-database.yml, apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, apps/example/public/assets/logo.svg, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/LoaderRow.tsx, packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/components/inputs/Selector.tsx, packages/next-admin/src/hooks/useCloseOnOutsideClick.ts
Add loader to select - and fix click outside the block 
#364
=> Add loader to select

.changeset/strange-waves-rush.md, .github/workflows/reset-database.yml, apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx, apps/example/options.tsx, apps/example/pageRouterOptions.tsx, apps/example/public/assets/logo.svg, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/LoaderRow.tsx, packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx, packages/next-admin/src/components/inputs/SelectWidget.tsx, packages/next-admin/src/components/inputs/Selector.tsx, packages/next-admin/src/hooks/useCloseOnOutsideClick.ts
Reverts premieroctet/next-admin#370
=> Revert "Revert "Add loader to select""

.changeset/slimy-peas-move.md, packages/next-admin/package.json, packages/next-admin/src/components/ActionsDropdown.tsx, packages/next-admin/src/components/ExportDropdown.tsx, packages/next-admin/src/components/Menu.tsx, packages/next-admin/src/components/inputs/Selector.tsx, yarn.lock
Upgrade headless ui to v2
#396
=> chore: upgrade to headlessui v2

.changeset/small-dots-greet.md, packages/next-admin/src/components/Menu.tsx
Fix use picture
#420 
Set `width` and `height` to image tag
=> Fix user picture

.changeset/giant-flowers-smoke.md, apps/docs/pages/docs/api/model-configuration.mdx, apps/example/messages/fr.json, apps/example/options.tsx, packages/next-admin/src/appHandler.ts, packages/next-admin/src/components/ActionDropdownItem.tsx, packages/next-admin/src/components/ActionsDropdown.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/ListHeader.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/components/radix/Tooltip.tsx, packages/next-admin/src/hooks/useAction.ts, packages/next-admin/src/i18n.ts, packages/next-admin/src/pageHandler.ts, packages/next-admin/src/types.ts, packages/next-admin/src/utils/options.ts, packages/next-admin/src/utils/prisma.ts, packages/next-admin/src/utils/props.ts, packages/next-admin/src/utils/server.ts
Add conditional action
#430 
Add `canExecute` to actions options to allow specific record to execute the action
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
You can now use `canExecute` option. This gives you access to a 2-deep object, and you must return a boolean
=> Conditional action

.changeset/heavy-trainers-cover.md, packages/next-admin/src/components/advancedSearch/AdvancedSearchDropdown.tsx, packages/next-admin/src/components/advancedSearch/AdvancedSearchModal.tsx, packages/next-admin/src/components/advancedSearch/AdvancedSearchTreeItem.tsx, packages/next-admin/src/components/radix/Dialog.tsx
Improve the UI of the dialog modal
=> feat: improve dialog design

.changeset/large-radios-unite.md, apps/example/messages/en.json, apps/example/messages/fr.json, apps/example/options.tsx, packages/next-admin/src/context/FormDataContext.tsx, packages/next-admin/src/hooks/useAction.ts
- Refresh on action performed (list and form) - in case action change current model, data needs to refresh
- Add filters for example demo
=> Add refresh on action perform and add filters on example

.changeset/seven-ties-mate.md, apps/example/actions/addTag.ts, apps/example/components/PostAddTagDialogContent.tsx, apps/example/components/UserDetailsDialogContent.tsx, apps/example/messages/en.json, apps/example/messages/fr.json, apps/example/options.tsx, packages/next-admin/src/context/ClientActionDialogContext.tsx
=> Add refresh on dialog client and add options on example

.changeset/calm-beers-prove.md, packages/cli/src/utils/tailwind.ts
=> fix: remove useless headlessui tailwind plugin

.changeset/wise-snakes-boil.md, packages/next-admin/src/components/inputs/SelectWidget.tsx
Fix nullable relationship
#471
=> Nullable realtionship

.changeset/chilled-mice-approve.md, packages/next-admin/src/utils/advancedSearch.ts
Fix error when use advanced filters on nullable relationship field
#481 
There was error when using advanced filters on nullable relationship field
No impact
=> Fix advanced filter on nullable field

.changeset/long-cameras-arrive.md, packages/next-admin/src/components/inputs/DndItem.tsx
Fix drag & drop on touch devices
#461
=> fix: dnd on touch devices

.changeset/poor-donuts-deny.md, packages/next-admin/package.json, pnpm-lock.yaml
Upgrade heroicons to v2.2.0
#505
=> chore: upgrade heroicons

.changeset/serious-hounds-kiss.md, .changeset/tough-tools-applaud.md, apps/example/pageRouterOptions.tsx, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/inputs/FileWidget/FileWidget.tsx, packages/next-admin/src/components/radix/Dialog.tsx, packages/next-admin/src/utils/server.ts, packages/next-admin/src/utils/tools.ts
=> Small Fixes

.changeset/twelve-cats-dance.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/MainLayout.tsx, packages/next-admin/src/components/Message.tsx, packages/next-admin/src/components/index.ts, packages/next-admin/src/index.ts
Export `<Message />` component, to usage in custom pages
=> Export Message component

.changeset/breezy-lions-deliver.md, apps/docs/pages/docs/api/model-configuration.mdx, apps/example/options.tsx, packages/next-admin/src/hooks/useDataColumns.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/prisma.ts
Add support for virtual fields, to compute a value from other columns
#559 
Add the ability to add custom columns which are the results of the computation of other columns of a row. This value can be formatted as a string or a react element (currently only for app router).
=> feat: virtual fields

.changeset/rotten-timers-repair.md, packages/next-admin/src/components/Form.tsx, packages/next-admin/src/components/List.tsx, packages/next-admin/src/components/NextAdmin.tsx, packages/next-admin/src/context/ClientActionDialogContext.tsx, packages/next-admin/src/types.ts, packages/next-admin/src/utils/options.ts, packages/next-admin/src/utils/props.ts
Fix an error in prod build with client actions dialog
=> fix: client dialog action error in prod build

.changeset/selfish-kings-marry.md, packages/next-admin/src/appHandler.ts
Remove a forgotten log in the app handler
#617
=> chore: remove forgotten log in app handler
