- .changeset/field-formatter.md
- apps/docs/pages/docs/api-docs.mdx
- apps/example/pages/admin/[[...nextadmin]].tsx
- packages/next-admin/src/components/Cell.tsx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/NextAdmin.tsx
- packages/next-admin/src/components/inputs/MultiSelectWidget.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/server.ts
Fix https://github.com/premieroctet/next-admin/issues/14
This allow user to specify a formatter for fields 
```
export default function Admin(props: AdminComponentProps) {
return <NextAdmin {...props} dashboard={Dashboard} options={{
model: {
user: {
list: {
fields: {
role: {
formatter: (user) => {
return <strong>{user.role as string}</strong>;
},
}
}
}
}
}
}} />;
}
```
> feat: field formatter option

- .changeset/sharp-bulldogs-appear.md
- packages/next-admin/src/utils/prisma.ts
**Issue**
#107 
**Change**
- Remove `mode` on search when Prisma don't have `QueryMode` property (e.g MySQL databases)
> Fix insensitive search for MySQL provider

- .changeset/cyan-wombats-appear.md
- packages/next-admin/src/router.tsx
- packages/next-admin/src/utils/server.ts
**Issues**
#153 #138 
**Changes**
- Allow access to sublevel object in select options items, for `optionFormatter` function
> Fix sublevel item on select

- packages/next-admin/src/components/ColorSchemeSwitch.tsx
- packages/next-admin/src/components/MainLayout.tsx
- packages/next-admin/src/components/Menu.tsx
- packages/next-admin/src/context/ColorSchemeContext.tsx
Fix color scheme switch rendering
- Move the color scheme switch rendering on the client side to avoid hydration issues
- Add an icon for the `system` scheme
Change the schemes, check that there is no hydration error upon refreshing
> fix: scheme switch hydration and client rendering

- .changeset/giant-badgers-tickle.md
- apps/docs/pages/docs/api-docs.mdx
- apps/example/components/DatePicker.tsx
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/CheckboxWidget.tsx
- packages/next-admin/src/components/inputs/FileWidget.tsx
- packages/next-admin/src/components/inputs/JsonField.tsx
- packages/next-admin/src/components/inputs/MultiSelectItem.tsx
- packages/next-admin/src/components/inputs/MultiSelectWidget.tsx
- packages/next-admin/src/components/inputs/RichText/RichTextField.tsx
- packages/next-admin/src/components/inputs/RichText/components.tsx
- packages/next-admin/src/components/inputs/SelectWidget.tsx
- packages/next-admin/src/components/radix/Switch.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/jsonSchema.ts
Add the possibility to disable some fields for a model
Add a `disabled` property in the fields edit options for a model. This would impact the UI of the field, giving it an opacity of 50% and making it not editable.
For custom inputs, a `disabled` prop is passed.
Example on the Post model with the `title`, `content` and `published` fields disabled
Example with the `author` field disabled
The interactions that don't have impact on the content of the form are still possible, for example here we still can go to the author's edit page.
> feat: add possibility to disable fields

- .changeset/tricky-days-add.md
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/MultiSelectWidget.tsx
- packages/next-admin/src/components/inputs/SelectWidget.tsx
- packages/next-admin/src/components/inputs/Selector.tsx
Improve dropdown SelectWIdget and MultiselectWidget
#236
- Filter all fetched options in dropdown and keep only those that are not already selected
- Use `intersectionObserver `to detect last row is reached and fetch next page data
No impact
> Filter options with selected options dropdown

- .changeset/green-apples-eat.md
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Fix sort for many-to-one relationships in list
#248 
We only handled sorting on many-to-many or one-to-many relationships. We now have a condition to set the correct orderBy field in the prisma request depending on the relationship.
> fix: sort many-to-one relationship in list

- .changeset/new-needles-sort.md
- apps/example/options.tsx
- apps/example/pageRouterOptions.tsx
- packages/next-admin/src/components/Cell.tsx
- packages/next-admin/src/utils/prisma.ts
Fix formatting for boolean fields
#249 
There was an issue in the formatter where the boolean fields did not pass a condition because of an incorrect check. The issue was also present on page router.
Add a formatter for the `published` field of the `Post` model in the example app. Check and uncheck the toggle in the edit form. The value should be formatted as `Published` or `Unpublished` on the list.
> fix: formatter on boolean fields

- .changeset/shaggy-pumpkins-help.md
- apps/docs/pages/docs/i18n.mdx
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/hooks/useDeleteAction.ts
- packages/next-admin/src/i18n.ts
Add deletion message customization, with i18n compat
#254 
Add keys to the i18n messages and add them in the `useDeleteAction` hook
> feat: add deletion message customization

- .changeset/itchy-lions-relate.md
- apps/example/options.tsx
- apps/example/pageRouterOptions.tsx
- packages/next-admin/src/components/inputs/FileWidget.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/server.ts
Enhance FileWidget in form
Enhance FileWidget
Change the `upload` function to take a File object (more file information) instead of a Buffer object.
Preview on file change with `readAsDataURL` 
Type of `upload` function changes to take a File object.
> Enhance FileWidget in form

- .changeset/poor-planes-repeat.md
- apps/docs/pages/docs/api-docs.mdx
- apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx
- apps/example/e2e/001-crud.spec.ts
- apps/example/options.tsx
- apps/example/pageRouterOptions.tsx
- packages/next-admin/src/components/Filters.tsx
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/CheckboxWidget.tsx
- packages/next-admin/src/components/inputs/DateTimeWidget.tsx
- packages/next-admin/src/components/inputs/FileWidget.tsx
- packages/next-admin/src/components/inputs/JsonField.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx
- packages/next-admin/src/components/inputs/RichText/RichTextField.tsx
- packages/next-admin/src/components/inputs/RichText/utils.tsx
- packages/next-admin/src/components/inputs/SelectWidget.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/jsonSchema.ts
- packages/next-admin/src/utils/server.ts
Add `required` on form fields option to apply HTML validation on these fields
#257 
Add `required` to true on field options, note that if this fields is already required according to the Prisma schema you cannot remove the `required`
New test end2end as `user create client error`
No impact
> Add required options on edit fields

- .changeset/curvy-lobsters-eat.md
- apps/docs/pages/docs/api-docs.mdx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Add row context to formatter function param `context`
#334 
Allow access to current row on context param of formatter field function. This row represents a non-formatter data for current row
No Impact
> Add row context

- .changeset/neat-doors-drive.md
- apps/example/options.tsx
- packages/next-admin/src/components/EmptyState.tsx
Disable creation button on list based on permission
On list page, disable creation button if user don't have permissions to create entity
No impact
> Disable creation button on list based on permission

- .changeset/khaki-frogs-carry.md
- packages/next-admin/src/utils/server.ts
Set null value instead of empty string
#345 
When field is empty, formData will send `""` (empty string) value, but this value will turn into `null` before submit formData with Prisma
No Impact
> Set null value instead of empty string

- .changeset/plenty-cooks-smile.md
- packages/next-admin/src/components/inputs/RichText/RichTextField.tsx
- packages/next-admin/src/components/inputs/RichText/utils.tsx
Auto minify all HTML from database when using richtext input, add support of div for external set of this fields
#347 
No Impact
> Note that if you put html directly into you database and try to see it in nextadmin you need to make sure that this is a valid HTML and that it does not contain unsupported tags
> Minify html for richtext and support div

- .changeset/six-cherries-explain.md
- packages/next-admin/src/components/inputs/SelectWidget.tsx
Fix selection in form for Safari browser
#355 
Fix selection in form for Safari browser. Problem due to required selection on Safari Browser
test e2e of CRUD
No impact
> Fix selection in form for Safari browser

- .changeset/eight-buses-admire.md
- packages/next-admin/src/components/ExportDropdown.tsx
- packages/next-admin/src/components/ListHeader.tsx
NextJS automatically prefetch all `<Link/>` and cause `404` when trying to prefetch Exports link
> Don't prefetch export Link

- .changeset/great-bees-pump.md
- .changeset/pre.json
- .github/workflows/e2e.yml
- apps/docs/package.json
- apps/example/options.tsx
- apps/example/package.json
- apps/example/pageRouterOptions.tsx
- packages/next-admin/CHANGELOG.md
- packages/next-admin/package.json
- packages/next-admin/src/components/inputs/FileWidget.tsx
- packages/next-admin/src/utils/file.test.ts
- packages/next-admin/src/utils/file.ts
Fetching image in `<FileWidget/>` component could cause CORS errors
This PR changes the file detection behaviour in the `<FileWidget/>` component. 
We don't use `fetch` anymore. We detect the type of the file (image or other type of file) and the name via the URL of the file.
Added test for each new utils/file.ts functions created
No particular impact but it is important to mention that we don't handle the case where the image is hosted on a URL that doesn't directly point to a file (ex: `http://site/image.png`). So `http://site/image?w=300&h=300` would not work.
Updated e2e.yml to fix a GH actions error
> fix: file widget cors error

- .changeset/rotten-beds-allow.md
- apps/docs/pages/docs/api/options.mdx
- packages/next-admin/src/components/Menu.tsx
- packages/next-admin/src/components/NextAdmin.tsx
- packages/next-admin/src/types.ts
#380 
#381 
1. Having warning in terminal is always disturbing. This warning could be easily removed by just importing it dynamically.
2. In admin panel sidebar it was hard to differentiate between group title and model name. Allowing user to add custom css classes will make group title more easily recognizable.
Nothing added
1. There will be no warning
2. User will be able to customize looks of group title in sidebar
Nothing
> Removes warning "You're using next/head inside the app directory" and Feature to add css classes to sidebar group title

- .changeset/curly-penguins-explode.md
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectDisplayListItem.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectItem.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/server.ts
Add support for arrays of enums.
#322 
- Based on #389, added support for arrays of enums reusing the `MultiSelectWidget` component.
- Also added some more types to be able to define either `list` or `select` as display when the edit field selected is an array of a Enum. 
https://github.com/user-attachments/assets/9bf05f7c-506e-4e6a-9e62-7b9037aa9603
> feat: add support to array of enums

- .changeset/curly-penguins-explode.md
- .changeset/stupid-suits-report.md
- apps/docs/pages/docs/i18n.mdx
- apps/example/e2e/utils.ts
- apps/example/options.tsx
- apps/example/pageRouterOptions.tsx
- apps/example/prisma/json-schema/json-schema.json
- apps/example/prisma/migrations/20240902093202_tags_on_post/migration.sql
- apps/example/prisma/schema.prisma
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/BaseInput.tsx
- packages/next-admin/src/components/inputs/DndItem.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectDisplayListItem.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectItem.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx
- packages/next-admin/src/components/inputs/ScalarArray/ScalarArrayField.tsx
- packages/next-admin/src/components/inputs/ScalarArray/ScalarArrayFieldItem.tsx
- packages/next-admin/src/i18n.ts
- packages/next-admin/src/tests/prismaUtils.test.ts
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
- packages/next-admin/src/utils/props.ts
- packages/next-admin/src/utils/server.ts
Add support for Prisma scalar array 
#322 
Add support for Prisma scalar arrays. Currently supported scalar types are strings and numbers.
In the list, the array is displayed as a count. The PR also includes support search inside the array (case sensitive & exact content as its the only supported way on Prisma)
> feat: add support for scalar array

- .changeset/chilled-eggs-brush.md
- apps/example/options.tsx
- packages/next-admin/src/utils/server.ts
Fix one-to-one relationship display in list
#393 
On our formatting for row cells, we are checking for the relationship type depending on what the DMMF says. It seems that for one-to-one relations, the DMMF indicates a relation on one side but not the other. So on the side which does not give the info, we add an extra check on the `isList` property.
> fix: fix one-to-one display for one side

- .changeset/brave-shirts-cross.md
- apps/docs/pages/docs/api/model-configuration.mdx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/props.ts
- packages/next-admin/src/utils/server.ts
Allow controlling the visibility of an edit field with a function
#372 
Add a function in the edit fields options that takes the resource value as parameter and returns a boolean that will show or hide the field in the edit form.
> feat: allow controlling the visibility of an edit field

- .changeset/hungry-poets-lie.md
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/example/options.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.test.ts
- packages/next-admin/src/utils/prisma.ts
Add the ability to search in the list in relations
#385 
Currently the search on the list page can only be done on scalar fields. This PR adds the ability to trigger the search on nested relations.
Example:
```ts
const options: NextAdminOptions = {
model: {
Post: {
list: {
search: ["title", "author.name", "author.email", "author.posts.title"],
},
},
},
};
```
In the typing, the depth of nesting has been set to 4, but in theory if you ignore typing, it will go as deep as needed
A search on `author.name` has been applied on the Post model, so a simple test could be to run some search into the Post model.
> feat: add search by relation

- .changeset/cool-cycles-do.md
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/docs/pages/docs/code-snippets.mdx
- apps/example/options.tsx
- packages/next-admin/src/appHandler.ts
- packages/next-admin/src/exceptions/HookError.ts
- packages/next-admin/src/handlers/resources.ts
- packages/next-admin/src/index.ts
- packages/next-admin/src/pageHandler.ts
- packages/next-admin/src/types.ts
- turbo.json
Add new `hooks` field on a model's `edit` property
#386 
The current way to intercept data creation / edition is quite trivial and can result in complex code in the `POST` handler. This PR allows adding 2 new hooks under the `edit` property of a model :
- `beforeDb` which is executed before inserting / updating the data in the database. This allows adding or modifying some data in the values that are about to be inserted. It receives 3 parameters:
- `data` -> the form values that are about to be inserted
- `mode` -> either `create` or `edit`
- `request` -> the origin request. [NextRequest](https://nextjs.org/docs/app/api-reference/functions/next-request) for App Router, [NextApiRequest](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#parameters) for Page Router …
> feat: add hooks to model edition

- .changeset/eight-trainers-judge.md
- packages/next-admin/src/components/EmptyState.tsx
Default empty state to title before the resource in lowercase.
#400 
Right now, the empty state is using translations to show the name of the resource, and if the translation is not present, it's showing the resource name in lowercase as fallback. With this PR, instead of showing that, we show the resource title that was set in the options file (if present).
> fix: default empty state to title before resource in lowercase

- .changeset/chilled-baboons-warn.md
- apps/example/prisma/migrations/20240907035434_add_hashed_password_field/migration.sql
- apps/example/prisma/schema.prisma
Fix the User schema for hashedPassword
> fix: set hashed password optional

- .changeset/clever-coins-teach.md
- packages/next-admin/src/utils/server.ts
Fix crash when edit options are not defined
[Linked issues]
If model object doesn't define `edit: {}` it is crashing admin panel. It originated in https://github.com/premieroctet/next-admin/pull/406
`yarn test` passes.
Nothing.
Nothing.
> fix: crash when options.model.edit is not defined

- .changeset/shiny-clouds-appear.md
- apps/docs/pages/docs/code-snippets.mdx
- apps/docs/pages/docs/getting-started.mdx
- apps/docs/pages/docs/theming.mdx
- apps/docs/pages/docs/v5-migration-guide.mdx
- apps/example/app/[locale]/admin/[[...nextadmin]]/page.tsx
- apps/example/app/[locale]/admin/custom/page.tsx
- apps/example/app/api/admin/[[...nextadmin]]/route.ts
- apps/example/pages/api/pagerouter/admin/[[...nextadmin]].ts
- apps/example/pages/pagerouter/admin/[[...nextadmin]].tsx
- apps/example/pages/pagerouter/admin/custom/index.tsx
- apps/example/prisma/json-schema/json-schema.json
- apps/example/tailwind.config.js
- apps/example/tsconfig.json
- packages/next-admin/package.json
- packages/next-admin/src/index.ts
- packages/next-admin/tsconfig.json
- packages/tsconfig/nextjs.json
Use package.json `exports` field.
#379 
This PR introduces a breaking change to the way we import stuff from inside the `dist folder`.
Example
`import { getNextAdminProps } from "@premieroctet/next-admin/dist/appRouter"`
now becomes
`import { getNextAdminProps } from "@premieroctet/next-admin/appRouter"`
This is a breaking change, this impacts all the imports that are pointing to the `dist` folder. Those will need to be changed across all JS/TS files, and in the Tailwind config file aswell
> feat: use exports field

- .changeset/perfect-toys-bathe.md
- apps/docs/pages/docs/api/components.mdx
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/example/components/UserDetailsDialogContent.tsx
- apps/example/messages/en.json
- apps/example/messages/fr.json
- apps/example/options.tsx
- packages/next-admin/package.json
- packages/next-admin/src/appHandler.ts
- packages/next-admin/src/components/ActionDropdownItem.tsx
- packages/next-admin/src/components/ActionsDropdown.tsx
- packages/next-admin/src/components/ClientActionDialog.tsx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/ListHeader.tsx
- packages/next-admin/src/components/NextAdmin.tsx
- packages/next-admin/src/components/advancedSearch/AdvancedSearchModal.tsx
- packages/next-admin/src/components/index.ts
- packages/next-admin/src/components/radix/Dialog.tsx
- packages/next-admin/src/components/radix/Dropdown.tsx
- packages/next-admin/src/context/ClientDialogContext.tsx
- packages/next-admin/src/hooks/useAction.ts
- packages/next-admin/src/index.ts
- packages/next-admin/src/pageHandler.ts
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/options.ts
- packages/next-admin/src/utils/props.ts
- packages/tsconfig/base.json
Add the ability to render client component through list row actions
#401 
Currently, row actions only allows to execute a set of actions that are executed on the server side through an API call. This is limiting when we want to visualize some stuff on the client side. This PR allows defining client only actions that accept a component property (like custom inputs) and renders it in a Dialog box.
> feat: add client actions

- .changeset/breezy-cups-call.md
- packages/next-admin/src/components/advancedSearch/AdvancedSearchDropdownItem.tsx
- packages/next-admin/src/components/radix/Dialog.tsx
- packages/next-admin/src/context/I18nContext.tsx
- packages/next-admin/src/hooks/useAdvancedSearch.ts
- packages/next-admin/src/utils/advancedSearch.test.ts
- packages/next-admin/src/utils/advancedSearch.ts
Correctly display path in advanced search. The path was not displaying correctly after doing an advanced search and refreshing the page, or simply re-opening the modal.
> fix: correctly display path in advanced search

- .changeset/fuzzy-socks-visit.md
- .changeset/honest-emus-breathe.md
- apps/docs/pages/docs/getting-started.mdx
- packages/cli/src/commands/init.ts
- packages/cli/src/templates/page_router_page.mustache
- packages/cli/src/utils/next.ts
- packages/next-admin/src/pageRouter.ts
Fixes some issues with page router both with the CLI and the lib
#452 
This PR fixes some issues with the Page Router : 
- on the library side, we were not passing the locale prop to `getNextAdminProps`
- on the CLI side, we were generating content with syntax errors and an invalid CSS import. We also needed to add instructions about SuperJson configuration.
> fix: CLI for page router, locale in page router props

- .changeset/early-carpets-notice.md
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/next.ts
Add missing package name in instructions for Page Router in CLI
> fix: add missing package name in install instructions in CLI

- .changeset/metal-ties-help.md
- packages/next-admin/src/utils/server.ts
Fix a crash that was occuring when dmmf's relationship arrays were undefined
#465
> fix: crash on undefined relationship length

- .changeset/dull-cows-thank.md
- packages/next-admin/src/components/Cell.tsx
Correctly display boolean values in list when no formatter is provided
#466
> fix: display correctly boolean value in list

- .changeset/dry-tips-thank.md
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/example/options.tsx
- packages/next-admin/src/appHandler.ts
- packages/next-admin/src/components/ClientActionDialog.tsx
- packages/next-admin/src/pageHandler.ts
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
- packages/next-admin/src/utils/server.ts
Add depth selection for raw data actions
#443 
Add the possibility to select a depth for raw data query for actions. This should be use with caution since a number too high could potentially cause slower queries.
> feat: add depth selection for actions

- .changeset/selfish-rules-bathe.md
- packages/next-admin/src/components/Menu.tsx
Replace the gear icon to a logout icon, since the existing dropdown doesn't contain anything else than a logout button
#460
> feat: update gear icon to logout icon

- .changeset/sweet-ads-drum.md
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/example/options.tsx
- packages/next-admin/src/components/Badge.tsx
- packages/next-admin/src/components/Filters.tsx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
- packages/next-admin/src/utils/props.ts
Add the possibility to retrieve filters dynamically
#491
This PR adds the possibility to pass an async function to the filters array, which will return an array of filters.
This also adds the possibility to group filters by an id to give the filters with the same group name a radio button like behavior.
Dynamic filters have been setup in the example app on the Post model
> feat: add dynamic filters

- .changeset/thin-flowers-prove.md
- apps/docs/pages/docs/getting-started.mdx
- packages/cli/src/commands/init.ts
Add a note in the doc and in the CLI for the suppressHydrationWarning prop
#492 
This relates to a hydration error that occurs with React 19 and Next 15 where next-themes would cause a hydration error. Per [the documentation](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app) we need to add the `suppressHydrationWarning` prop in the closest root layout to make this disappear.
> chore: add note about hydration warning for next-themes

- .changeset/sharp-eggs-hang.md
- .github/workflows/e2e.yml
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/components/inputs/ArrayField.tsx
- packages/next-admin/src/components/inputs/JsonField.tsx
- packages/next-admin/src/components/inputs/ScalarArray/ScalarArrayField.tsx
- packages/next-admin/src/components/inputs/ScalarArray/ScalarArrayFieldItem.tsx
- packages/next-admin/src/types.ts
Allow custom inputs in array fields
#510
> Allow custom inputs in array fields

- .changeset/seven-dolphins-clap.md
- packages/next-admin/package.json
- packages/next-admin/src/components/ClientActionDialog.tsx
- packages/next-admin/src/components/radix/VisuallyHidden.tsx
- pnpm-lock.yaml
Fix Dialog title and description errors thrown by radix for custom dialog
#520
> fix: Dialog title and description errors

- .changeset/great-kings-grin.md
- packages/next-admin/src/components/Menu.tsx
- packages/next-admin/src/components/NextAdmin.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/props.ts
Support passing a React Node as the title displayed on the menu.
#512
> feat: support react node as title

- .changeset/soft-wasps-kneel.md
- apps/example/package.json
- package.json
- packages/generator-prisma/src/index.ts
- turbo.json
Update path of the generated JSON Schema
#504 
This is an attempt to fix an issue that arised with PNPM, because of the way PNPM installs the packages, the .next-admin folder which contains the JSON schema was generated in a place that could not be resolved by Node.
This fix generates the schema in the node_modules of the `next-admin` package, which should make it accessible.
> fix: move generated json schema

- .changeset/clean-dolphins-report.md
- apps/example/options.tsx
- packages/generator-prisma/src/dmmf.ts
Fix display of one-to-many fields in create and edit form
#513
> fix: remove anyOf for one-to-many relations

- .changeset/long-bobcats-cough.md
- packages/next-admin/src/appHandler.ts
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/handlers/resources.ts
- packages/next-admin/src/hooks/useDeleteAction.ts
- packages/next-admin/src/pageHandler.ts
- packages/next-admin/src/types.ts
Add edit and delete middlewares
#527 #528
To give more granularity to the edition and deletion, we now provide a way to do stuff just before Prisma executes the update / delete queries. This gives the ability to interact with a remote CDN for example, where resource associated files can be accordingly added / removed.
> feat: add edit and delete middlewares

- .changeset/old-turkeys-speak.md
- apps/docs/pages/docs/api/model-configuration.mdx
- packages/next-admin/src/components/Pagination.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectDisplayList.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectDisplayTable.tsx
- packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx
- packages/next-admin/src/hooks/useLocalPagination.ts
- packages/next-admin/src/types.ts
Allow pagination on relationship fields display on the edit page
#542 
Add a new `pagination` property on a relationship edit field. it can be empty or contain `perPage` (defaults to 20).
> feat: allow pagination for relationship display

- .changeset/four-rabbits-reply.md
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Add support for multiple fields in `defaultSort`
#526 
This PR adds the possibility to set the `defaultSort` to either a simple object or an array of objects so that multiple sorts criteria are applied
> feat: add multiple defaultSort

- .changeset/modern-kids-wonder.md
- apps/docs/pages/docs/api/model-configuration.mdx
- apps/example/options.tsx
- packages/next-admin/src/components/inputs/FileWidget/FileWidget.tsx
- packages/next-admin/src/components/inputs/ScalarArray/ScalarArrayField.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/server.ts
Add max items scalar arrays
This adds the possibility to define the maximum items a scalar array can contain, with the `maxLength` property on an edit field.
> feat: add max items for scalar arrays

- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/TableHead.tsx
- packages/next-admin/src/hooks/useDataColumns.tsx
Disable header sort when `orderField` property is used
#362
> Disable header sort when orderField is used

- .changeset/tame-singers-notice.md
- apps/docs/pages/docs/api/model-configuration.mdx
- packages/next-admin/src/components/Message.tsx
- packages/next-admin/src/context/MessageContext.tsx
- packages/next-admin/src/hooks/useAction.ts
- packages/next-admin/src/types.ts
Allow passing custom component for server side actions
#514 
Allow passing custom component (must be client) for server side actions that will be used inside the `Message` component displayed atfer the action's execution, instead of a simple `p` HTML tag containing the message.
> feat: add new server side action component

- .changeset/itchy-apes-happen.md
- packages/next-admin/src/components/Cell.tsx
- packages/next-admin/src/hooks/useDataColumns.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Fix support for absolute URLs in virtual fields
Fixes an issue where passing absolute urls in the result of the `url` function of a virtual field concatenated them with the base admin path.
> fix: absolute url for virtual fields

- .changeset/cuddly-bats-allow.md
- apps/docs/pages/docs/api/model-configuration.mdx
- packages/next-admin/package.json
- packages/next-admin/src/components/Form.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils.ts
Add a new `item` prop to custom input props
https://github.com/premieroctet/next-admin/issues/405#issuecomment-2839923154
To be able to access the currently edited resource, this PR adds a new `item` prop that is passed to custom inputs. This is the *initial* value of the record. If we want to render stuff more dynamically, we can use the newly exported `useFormData` from `@premieroctet/next-admin/utils`
> feat: add custom input item data

- .changeset/thirty-cars-warn.md
- packages/next-admin/package.json
Fix the `@premieroctet/next-admin/utils` export path
> fix: wrong utils export

- .changeset/dirty-peas-divide.md
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/NextAdmin.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/props.ts
Fix display of functional filters for page router, which was displaying the function name instead of the result of the function call
> fix: page router display for functional filters

- .changeset/twelve-coats-occur.md
- apps/example/options.tsx
- packages/next-admin/src/tests/prismaUtils.test.ts
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Fix latency issue from Prisma on list
#581 
- Split the prisma request in the list, because of Prisma issue of latency when using `orderBy` and relation (even `count`)
- `formatter` function on list field take a number (count) for relation field OneToMany
- 
`formatter` function for OneToMany relation field accepts no more object type
> Fix latency on list

- .changeset/lazy-cups-serve.md
- apps/docs/pages/docs/getting-started.mdx
- apps/docs/pages/docs/theming.mdx
- apps/example-start/styles.css
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/tailwind.ts
- packages/next-admin/package.json
- packages/next-admin/rollup.config.ts
- packages/next-admin/src/components/ColorSchemeSwitch.tsx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/components/Menu.tsx
- packages/next-admin/src/hooks/useDataColumns.tsx
- packages/next-admin/src/theme.css
Add support for tailwind 4 by providing a CSS file for theming
#573 
Provide a theme CSS file that can be imported in main app CSS file to be used with Tailwind 4.
Maintenance wise, this has the impact to require the maintenance of 2 files for theming. In the future, we might want to deprecate Tailwind 3, but this is not a really big deal as the theme is not that big.
> feat: add support for tailwind 4

- .changeset/blue-dots-fly.md
- packages/next-admin/src/components/advancedSearch/AdvancedSearchDropdownItem.tsx
- packages/next-admin/src/utils/advancedSearch.test.ts
- packages/next-admin/src/utils/advancedSearch.ts
Fix advanced search displaying incorrectly for some relations
#602 
In some cases, we were incorrectly displaying some relations in the advanced search dropdown like if they were scalar fields, which is incorrect since we cannot apply search on them. This was because we were not referring to the `$ref` that was part of the `__nextadmin` field in the json schema.
> fix: advanced search on simple relations

- .changeset/eighty-moles-remember.md
- packages/next-admin/src/appHandler.ts
Fixes the way we call `initGlobals` in app handler for API.
#605
> fix: initGlobals in app handler

- .changeset/polite-birds-relate.md
- apps/docs/pages/docs/api/model-configuration.mdx
- packages/next-admin/src/components/List.tsx
- packages/next-admin/src/types.ts
- packages/next-admin/src/utils/prisma.ts
Add an option for the default size of a resource list
#616
> feat: add default list size option
